-- MySQL Script generated by MySQL Workbench
-- Thu Feb 17 14:05:48 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Immolaplace
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Immolaplace
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Immolaplace` DEFAULT CHARACTER SET utf8 ;
USE `Immolaplace` ;

-- -----------------------------------------------------
-- Table `Immolaplace`.`Emplacement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Immolaplace`.`Emplacement` (
  `ID_Emplacement` INT NOT NULL AUTO_INCREMENT,
  `Adresse` VARCHAR(45) NOT NULL,
  `Code_post` INT NOT NULL,
  `Commune` VARCHAR(45) NOT NULL,
  `Code_dept` INT NOT NULL,
  PRIMARY KEY (`ID_Emplacement`),
  UNIQUE INDEX `ID_Emplacement_UNIQUE` (`ID_Emplacement` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Immolaplace`.`Bien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Immolaplace`.`Bien` (
  `ID_Bien` INT NOT NULL AUTO_INCREMENT,
  `Surf_carr` FLOAT NOT NULL,
  `Code_type_loc` INT NOT NULL,
  `Type_loc` VARCHAR(45) NOT NULL,
  `Nb_pp` INT NOT NULL,
  `ID_Emplacement` INT NOT NULL,
  PRIMARY KEY (`ID_Bien`),
  UNIQUE INDEX `ID_Bien_UNIQUE` (`ID_Bien` ASC) VISIBLE,
  INDEX `fk_Bien_Emplacement_idx` (`ID_Emplacement` ASC) VISIBLE,
  CONSTRAINT `fk_Bien_Emplacement`
    FOREIGN KEY (`ID_Emplacement`)
    REFERENCES `Immolaplace`.`Emplacement` (`ID_Emplacement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Immolaplace`.`Transations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Immolaplace`.`Transations` (
  `ID_Transations` INT NOT NULL AUTO_INCREMENT,
  `Date_mut` DATE NOT NULL,
  `Val_fonc` DECIMAL NOT NULL,
  `Bien_ID_Bien` INT NOT NULL,
  PRIMARY KEY (`ID_Transations`),
  UNIQUE INDEX `ID_Transations_UNIQUE` (`ID_Transations` ASC) VISIBLE,
  INDEX `fk_Transations_Bien1_idx` (`Bien_ID_Bien` ASC) VISIBLE,
  CONSTRAINT `fk_Transations_Bien1`
    FOREIGN KEY (`Bien_ID_Bien`)
    REFERENCES `Immolaplace`.`Bien` (`ID_Bien`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
